name: Deploy on Push

on:
  push:  # Trigger the workflow on any push to the repository
    branches:
      - main  # Replace with the branch you want to monitor (e.g., 'main')

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get the latest code (optional)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH and execute the script on the remote server
      - name: Execute Deploy Script on Remote Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 68.183.91.126            # Remote server IP
          username: root                 # SSH username
          key: ${{ secrets.DROPLET1_SSH_PRIVATE_KEY }} # SSH private key from secrets
          script: |
            cd /root/integration_check/Integration_test
            ./deploy.sh
